# wirte code for clusterIP services

# deployment for event bus
# deployment is in bucktet apps/v1
apiVersion: apps/v1

# specify the kind of object we want to create
kind: Deployment

metadata:
  name: event-bus-depl
# to specify how this deployment should behave
spec:
  #number of pods we want to create running some perticuler image
  replicas: 1
  # selector takes a look at the all the different pod that has been ever created  with a label of app event-bus
  selector:
    matchLabels:
      app: event-bus
  # configuration forthe pod this deployment is going to create. here we aretelling to deployment that , we want this pod to have label of app event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          # adding no version/ adding lates makes sure that it gets the latest version
          image: syedaismatfarjana09/event-bus:latest

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    # tellthe service to direct any event with the label of app: event-bus
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
