apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  # routing rules for ingress controller
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # routing rules we need to apply to teach ingress controller how to take incoming trrafic and route the to different pods
  rules:
    # host here tels that all config here is for only posts.com. cause kubernetes can have lots of other apps in the cluster
    - host: posts.com
      http:
        paths:
          - path: /posts
            backend:
              serviceName: posts-clusterip-srv
              servicePort: 4000
